version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html:cached
    depends_on:
      - app
    container_name: base_web

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: example_db
      DB_USERNAME: root
      DB_PASSWORD: password
      APP_DEBUG: "true"
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/app/conf.d/local.ini:/usr/local/etc/php/conf.d/override.ini:ro
    depends_on:
      - db
    container_name: base_app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
    container_name: base_db
